all: kadai-a kadai-b kadai-c-frw-1 kadai-c-frw-8192 kadai-c-rw-1 kadai-c-rw-8192 kadai-d

kadai-a: kadai-a.c
	gcc -Wall -std=gnu99 kadai-a.c -o kadai-a

kadai-b: kadai-b.c
	gcc -Wall -std=gnu99 kadai-b.c -o kadai-b

kadai-c-frw-1: kadai-c-frw-1.c
	gcc -Wall -std=gnu99 kadai-c-frw-1.c -o kadai-c-frw-1

kadai-c-frw-8192: kadai-c-frw-8192.c
	gcc -Wall -std=gnu99 kadai-c-frw-8192.c -o kadai-c-frw-8192

kadai-c-rw-1: kadai-c-rw-1.c
	gcc -Wall -std=gnu99 kadai-c-rw-1.c -o kadai-c-rw-1

kadai-c-rw-8192: kadai-c-rw-8192.c
	gcc -Wall -std=gnu99 kadai-c-rw-8192.c -o kadai-c-rw-8192

kadai-d: kadai-d.c
	gcc -Wall -std=gnu99 kadai-d.c -o kadai-d

clean:
	rm kadai-a kadai-b kadai-c-frw-1 kadai-c-frw-8192 kadai-c-rw-1 kadai-c-rw-8192 kadai-d
